// Seed / refresh the Chennai heatmap zones from data/zones.js (single source of
// truth). Run:  node scripts/seedZones.js
//
// What it does:
//   1. Upserts all zones into Supabase `heatmap_zones` via service_role,
//      idempotently (delete-by-city then insert → exactly N rows, no dups,
//      even if the UNIQUE(city,area_name) constraint isn't applied yet).
//   2. Regenerates the frontend fallback src/data/heatmapZones.js.
//   3. Prints an INSERT … ON CONFLICT block to paste into supabase/schema.sql.
//
// NOTE: the live DB may not have the `source` column yet (added by the updated
// schema.sql). We insert the column set the current schema supports and keep
// `source` in the code fallbacks + the generated SQL.

require('dotenv').config()
const fs = require('fs')
const path = require('path')
const supabase = require('../lib/supabase')
const { SEED_ZONES } = require('../data/zones')

const FRONTEND_FILE = path.join(__dirname, '..', '..', 'src', 'data', 'heatmapZones.js')

function genFrontend() {
  const lines = SEED_ZONES.map((z) => {
    const o = {
      area_name: z.area_name,
      latitude: z.latitude,
      longitude: z.longitude,
      radius_m: z.radius_m,
      risk_level: z.risk_level,
      risk_score: z.risk_score,
      active_hours: z.active_hours,
      source: z.source,
    }
    return '  ' + JSON.stringify(o) + ','
  })
  return `// Local fallback for the crime heatmap (mirrors Supabase \`heatmap_zones\`).
// AUTO-GENERATED by backend/scripts/seedZones.js — edit backend/data/zones.js instead.
// Curated from public reporting (Safecity.in, NCRB, local news) — see SOURCES.md.
export const HEATMAP_ZONES = [
${lines.join('\n')}
]
`
}

function sqlEscape(s) {
  return String(s).replace(/'/g, "''")
}

function genSql() {
  const rows = SEED_ZONES.map((z) => {
    return `('${sqlEscape(z.area_name)}', '${z.city}', ${z.latitude}, ${z.longitude}, ${z.radius_m}, '${z.risk_level}', ${z.risk_score}, '${sqlEscape(z.reason)}', '${z.active_hours}', '${sqlEscape(z.source)}')`
  })
  return `INSERT INTO public.heatmap_zones
  (area_name, city, latitude, longitude, radius_m, risk_level, risk_score, reason, active_hours, source) VALUES
${rows.join(',\n')}
ON CONFLICT (city, area_name) DO UPDATE SET
  latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude, radius_m = EXCLUDED.radius_m,
  risk_level = EXCLUDED.risk_level, risk_score = EXCLUDED.risk_score, reason = EXCLUDED.reason,
  active_hours = EXCLUDED.active_hours, source = EXCLUDED.source;`
}

async function seedSupabase() {
  if (!supabase) {
    console.log('• Supabase not configured — skipping DB seed (env not set).')
    return { seeded: 0, ok: false }
  }
  // Column set the current live schema supports (no `source` until schema.sql
  // is re-applied). Delete-then-insert keeps it idempotent without needing the
  // UNIQUE constraint.
  const rows = SEED_ZONES.map(({ source, ...rest }) => rest) // eslint-disable-line no-unused-vars
  const del = await supabase.from('heatmap_zones').delete().eq('city', 'chennai')
  if (del.error) {
    console.error('• Delete failed:', del.error.message)
    return { seeded: 0, ok: false }
  }
  const ins = await supabase.from('heatmap_zones').insert(rows).select('id')
  if (ins.error) {
    console.error('• Insert failed:', ins.error.message)
    return { seeded: 0, ok: false }
  }
  return { seeded: ins.data.length, ok: true }
}

;(async () => {
  console.log(`Seeding ${SEED_ZONES.length} Chennai zones…`)

  fs.writeFileSync(FRONTEND_FILE, genFrontend())
  console.log(`• Wrote frontend fallback: ${path.relative(process.cwd(), FRONTEND_FILE)}`)

  const sqlOut = path.join(__dirname, 'zones.generated.sql')
  fs.writeFileSync(sqlOut, genSql() + '\n')
  console.log(`• Wrote SQL: ${path.relative(process.cwd(), sqlOut)}`)

  // DB write is gated behind SEED_DB=1 — it mutates the shared Supabase table,
  // so it's opt-in. Default run only regenerates local files (non-destructive).
  if (process.env.SEED_DB === '1') {
    const { seeded, ok } = await seedSupabase()
    if (ok) {
      const { count } = await supabase
        .from('heatmap_zones')
        .select('*', { count: 'exact', head: true })
        .eq('city', 'chennai')
      console.log(`• Supabase seeded: ${seeded} rows (table now has ${count} chennai zones)`)
    }
  } else {
    console.log('• Skipped Supabase write (set SEED_DB=1 to seed the shared DB).')
  }
  console.log('Done.')
  process.exit(0)
})()
